workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - rstodoappkey
      vars:
        PACKAGE_NAME: 'com.rstodoapp'
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Ensure gradlew is executable
        script: |
          chmod +x android/gradlew
      - name: Build Android release
        script: |
          cd android
          ./gradlew clean bundleRelease --no-daemon --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - praveen@resiliencesoft.com
        notify:
          success: true
          failure: true
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
